name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint (errors only)
        run: npx eslint src server tests --quiet
        continue-on-error: false

      - name: Run ESLint (full report with warnings)
        run: npm run lint || true
        if: always()

      - name: Build project
        run: npm run build

      - name: Run unit tests
        run: npm run test:unit